-- Fictional local-only seed; no deliverable mailbox or usable visitor credential.
INSERT INTO identities(id,token_hash) VALUES('demo-reader','not-a-credential') ON CONFLICT DO NOTHING;
INSERT INTO pages(path,title) VALUES('/playground','Hitalk 本地示例') ON CONFLICT DO NOTHING;
INSERT INTO comments(id,page_id,author_id,client_request_id,request_hash,nick,content_md,is_pinned) VALUES('demo-1',(SELECT id FROM pages WHERE path='/playground'),'demo-reader','request-1','seed','示例读者','本地评论 1 — **Markdown** 与表情 :smile:',1) ON CONFLICT DO NOTHING;
INSERT INTO comments(id,page_id,author_id,client_request_id,request_hash,nick,content_md,is_pinned) VALUES('demo-2',(SELECT id FROM pages WHERE path='/playground'),'demo-reader','request-2','seed','示例读者','本地评论 2 — **Markdown** 与表情 :smile:',0) ON CONFLICT DO NOTHING;
INSERT INTO comments(id,page_id,author_id,client_request_id,request_hash,nick,content_md,is_pinned) VALUES('demo-3',(SELECT id FROM pages WHERE path='/playground'),'demo-reader','request-3','seed','示例读者','本地评论 3 — **Markdown** 与表情 :smile:',0) ON CONFLICT DO NOTHING;
INSERT INTO comments(id,page_id,author_id,client_request_id,request_hash,nick,content_md,is_pinned) VALUES('demo-4',(SELECT id FROM pages WHERE path='/playground'),'demo-reader','request-4','seed','示例读者','本地评论 4 — **Markdown** 与表情 :smile:',0) ON CONFLICT DO NOTHING;
INSERT INTO comments(id,page_id,author_id,client_request_id,request_hash,nick,content_md,is_pinned) VALUES('demo-5',(SELECT id FROM pages WHERE path='/playground'),'demo-reader','request-5','seed','示例读者','本地评论 5 — **Markdown** 与表情 :smile:',0) ON CONFLICT DO NOTHING;
INSERT INTO comments(id,page_id,author_id,client_request_id,request_hash,nick,content_md,is_pinned) VALUES('demo-6',(SELECT id FROM pages WHERE path='/playground'),'demo-reader','request-6','seed','示例读者','本地评论 6 — **Markdown** 与表情 :smile:',0) ON CONFLICT DO NOTHING;
INSERT INTO comments(id,page_id,author_id,client_request_id,request_hash,nick,content_md,is_pinned) VALUES('demo-7',(SELECT id FROM pages WHERE path='/playground'),'demo-reader','request-7','seed','示例读者','本地评论 7 — **Markdown** 与表情 :smile:',0) ON CONFLICT DO NOTHING;
INSERT INTO comments(id,page_id,author_id,client_request_id,request_hash,nick,content_md,is_pinned) VALUES('demo-8',(SELECT id FROM pages WHERE path='/playground'),'demo-reader','request-8','seed','示例读者','本地评论 8 — **Markdown** 与表情 :smile:',0) ON CONFLICT DO NOTHING;
INSERT INTO comments(id,page_id,author_id,client_request_id,request_hash,nick,content_md,is_pinned) VALUES('demo-9',(SELECT id FROM pages WHERE path='/playground'),'demo-reader','request-9','seed','示例读者','本地评论 9 — **Markdown** 与表情 :smile:',0) ON CONFLICT DO NOTHING;
INSERT INTO comments(id,page_id,author_id,client_request_id,request_hash,nick,content_md,is_pinned) VALUES('demo-10',(SELECT id FROM pages WHERE path='/playground'),'demo-reader','request-10','seed','示例读者','本地评论 10 — **Markdown** 与表情 :smile:',0) ON CONFLICT DO NOTHING;
INSERT INTO comments(id,page_id,author_id,client_request_id,request_hash,nick,content_md,is_pinned) VALUES('demo-11',(SELECT id FROM pages WHERE path='/playground'),'demo-reader','request-11','seed','示例读者','本地评论 11 — **Markdown** 与表情 :smile:',0) ON CONFLICT DO NOTHING;
INSERT INTO comments(id,page_id,author_id,client_request_id,request_hash,nick,content_md,is_pinned) VALUES('demo-12',(SELECT id FROM pages WHERE path='/playground'),'demo-reader','request-12','seed','示例读者','本地评论 12 — **Markdown** 与表情 :smile:',0) ON CONFLICT DO NOTHING;
INSERT INTO comments(id,page_id,author_id,root_id,reply_to_id,client_request_id,request_hash,nick,content_md) VALUES('demo-reply-1',(SELECT id FROM pages WHERE path='/playground'),'demo-reader','demo-1','demo-1','request-reply-1','seed','回复者','本地回复 1') ON CONFLICT DO NOTHING;
INSERT INTO comments(id,page_id,author_id,root_id,reply_to_id,client_request_id,request_hash,nick,content_md) VALUES('demo-reply-2',(SELECT id FROM pages WHERE path='/playground'),'demo-reader','demo-1','demo-1','request-reply-2','seed','回复者','本地回复 2') ON CONFLICT DO NOTHING;
INSERT INTO comments(id,page_id,author_id,root_id,reply_to_id,client_request_id,request_hash,nick,content_md) VALUES('demo-reply-3',(SELECT id FROM pages WHERE path='/playground'),'demo-reader','demo-1','demo-1','request-reply-3','seed','回复者','本地回复 3') ON CONFLICT DO NOTHING;
INSERT INTO comments(id,page_id,author_id,root_id,reply_to_id,client_request_id,request_hash,nick,content_md) VALUES('demo-reply-4',(SELECT id FROM pages WHERE path='/playground'),'demo-reader','demo-1','demo-1','request-reply-4','seed','回复者','本地回复 4') ON CONFLICT DO NOTHING;
INSERT INTO comment_likes(comment_id,identity_id) VALUES('demo-1','demo-reader') ON CONFLICT DO NOTHING;
INSERT INTO comment_likes(comment_id,identity_id) VALUES('demo-2','demo-reader') ON CONFLICT DO NOTHING;
INSERT INTO comment_likes(comment_id,identity_id) VALUES('demo-3','demo-reader') ON CONFLICT DO NOTHING;
INSERT INTO comment_likes(comment_id,identity_id) VALUES('demo-4','demo-reader') ON CONFLICT DO NOTHING;
INSERT INTO comment_likes(comment_id,identity_id) VALUES('demo-5','demo-reader') ON CONFLICT DO NOTHING;
INSERT INTO comment_likes(comment_id,identity_id) VALUES('demo-6','demo-reader') ON CONFLICT DO NOTHING;
INSERT INTO comment_likes(comment_id,identity_id) VALUES('demo-7','demo-reader') ON CONFLICT DO NOTHING;
INSERT INTO comment_likes(comment_id,identity_id) VALUES('demo-8','demo-reader') ON CONFLICT DO NOTHING;
INSERT INTO comment_likes(comment_id,identity_id) VALUES('demo-9','demo-reader') ON CONFLICT DO NOTHING;
INSERT INTO comment_likes(comment_id,identity_id) VALUES('demo-10','demo-reader') ON CONFLICT DO NOTHING;
